name: Run Scraper and Deploy Results

on:
  schedule:
    - cron: '0 10 * * 3'  # Every Tuesday at 10:00 AM UTC
   workflow_dispatch:  # Enables the "Run workflow" button
   
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the scraper
        run: python main.py

      - name: Commit and Push Results
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add results.html
          git commit -m "Update scraper results"
          git push origin main
