name: Run Scraper Weekly and Upload

on:
  schedule:
    - cron: '0 10 * * 2'  # Every Tuesday at 10:00 AM UTC

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the scraper
        run: python main.py

      - name: Upload via FTP
        run: |
          apt-get update && apt-get install -y ftp
          ftp -inv ${{ secrets.FTP_HOST }} <<EOF
          user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}
          binary
          cd public_html  # Change to your desired directory
          put results.html  # Upload the file
          bye
          EOF
